### ISSUE TITLE
Minecraft crashes after using trinkets with other mods

### ISSUE THREAD

**Issue by dudematthew** [emilyalexandra/trinkets#100]
While using Trinkets mod with a couple of other fabric mods I've encountered an issue, that was occuring while trying to get into any minecraft world

I'll try to discover what mod is uncompatibile as I think that's the problem

````---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 25.06.21 12:14
Description: Exception in server tick loop

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_3218.<init>(class_3218.java:209)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:410)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:335)
	at net.minecraft.class_1132.method_3823(class_1132.java:67)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$7336/853089235.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [adventurez.mixins.json:EnderDragonFightMixin] from phase [DEFAULT] in config [adventurez.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_2881::dragonKilledMixin with priority 1000 cannot inject into net/minecraft/class_2881::method_12528(Lnet/minecraft/class_1510;)V merged by ido.unlimiteddragoneggs.mixin.EnderDragonFightMixin with priority 1000 [PREINJECT Applicator Phase -> adventurez.mixins.json:EnderDragonFightMixin -> Prepare Injections ->  -> handler$zmg000$dragonKilledMixin(Lnet/minecraft/class_1510;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3497365504 bytes (3335 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.14.1+1.16.5
		adventurez: AdventureZ 1.2.6
		allure: Allure 1.2.8
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automated_crafting: Automated Crafting 1.3.21+MC1.16.2-1.16.5
		backslot: BackSlot 1.1.11
		battletowers: Battle Towers 3.3.4-1.16.4
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		betterend: Better End 0.9.6-pre
		betterf3: BetterF3 1.1.3
		betternether: Better Nether 5.0.7
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.0
		betterthirdperson: Better Third Person 1.5.0
		bigbeacons: Big Beacons 1.1.1
		blue_endless_jankson: jankson 1.2.0
		byg: BYG 1.1.8
		campanion: Campanion 1.3.5
		cardinal-components-base: Cardinal Components API (base) 2.5.0
		cardinal-components-entity: Cardinal Components API (entities) 2.5.0
		cavebiomes: Cave Biomes 0.6.2
		chains: Chains-Link 1.16.2-2.0.1
		cinderscapes: Cinderscapes 1.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.26
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		craftingpad: Crafting Pad 1.16.5-fabric0.30.0-1.0.5
		croptopia: Croptopia 1.4.0
		crowdin-translate: CrowdinTranslate 1.3+1.16
		customportalapi: Custom Portals 0.0.1-beta32-1.16
		dark-enchanting: Dark Enchanting 0.2.1+mc.1.16.5
		dark-loading-screen: Dark Loading Screen 1.6.3
		desolation: Desolation 1.1.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dungeonsmod: Dungeons Mod Lite 1.16.5-1.0.5
		dynamicfps: Dynamic FPS 2.0.2
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		easiervillagertrading: EasierVillagerTrading 1.16.5-fabric0.30.0-1.5.4
		enderitemod: Enderite Mod 1.2.4
		enhancedcelestials: Enhanced Celestials 1.0.2
		fabric: Fabric API 0.35.1+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.1.0+731c05f37d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+0ef801b67d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabric-tree-chopper: Fabric Tree Chopper 0.6.1
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.6.0+1.16.5
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		flytre_lib: FlytreLib 0.2.11
		food_highlight: FoodHighlight 1.0.1
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		geckolib3: Geckolib 3.0.40
		go-fish: Go Fish 1.2.3-beta-1.16.5
		gravestones: Gravestones v1.9
		greater_eye: Greater Eye of Ender 1.1.5
		horsestatsvanilla: Horse Stats Vanilla 4.1.7
		illuminations: Illuminations 1.5.1
		inmis: Inmis 2.2.1-1.16.5
		inventoryhud: Inventory HUD + 3.3.0
		inventorysorter: Inventory Sorter 1.7.9-1.16
		iris: Iris 1.0.0-rc1
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kirin: Kirin UI 1.7-1.16.2
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		lapisreserve: Lapis Reserve 1.0.7
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		libstructure: LibStructure 1.5
		mambience: MAmbience 3.1.1+1.16.5
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.16.9
		more_tooltips: MoreTooltips 1.0.1
		mostructures: Mo' Structures 1.2.0-1.16.5
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.4
		open2lan: Open To Lan 0.0.3
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		paradoxslabs: ParadoxSlabs 0.1.1
		particlerain: Particle Rain 1.2.1
		portaltags: Portal Tags 2.1.0
		presencefootsteps: Presence Footsteps r29+1.16.4
		quickshulker: Quick Shulker 1.1.14-1.16
		rare-ice: Rare Ice 0.2.2
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		repurposed_structures: Repurposed Structures 1.16.5-1.11.5-fabric
		reroll: Reroll 1.2.1-1.16.5
		riverredux: River Redux 0.1.6
		rocks: This Rocks! 1.3.1
		roughlyenoughitems: Roughly Enough Items 5.12.248
		roughlyenoughitems-api: REI (API) 5.12.248
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.248
		roughlyenoughitems-runtime: REI (Runtime) 5.12.248
		seamless_loading_screen: Seamless Loading Screen 1.3.4
		seedy-behavior: Seedy Behavior 1.0.1
		shulkerutils: shulkerutils 1.0.1-1.16
		sodium: Sodium 0.2.0+IRIS_rev.400af47
		spruceui: SpruceUI 2.0.4+1.16
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		stoneholm: Stoneholm 1.2.3
		structure-helpers: Structure Helpers 3.0.0
		stuffz: StuffZ 2.3.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		the_aether: The Aether 1.16.5-1.4.1
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.6
		transportables: Transportables 1.0.1
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		unlimiteddragoneggs: Unlimited Dragon Eggs 1.1.1
		untitledduckmod: Untitled Duck Mod 0.2.2
		voyager: Voyager 1.0.0
		waystones: Waystones 2.0.1
		wildworld: Wild World 2.0.0+1.16.5
		windchimes: Windchimes 1.1.1
		woodenhoppers: Wooden Hoppers 1.0.0
		xaerominimap: Xaero's Minimap 21.10.0.4
		yungsapi: YUNG's API 1.16.5-Fabric-5
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric

**Comment by dudematthew** [comment]
Update:

As I tried to eliminate mods one by one I discovered that even if I leave Fabric API & Trinkets it still doesn't load the world, being stuck at 2% of loading. No crush occured so I don't know how to diagnose.

**Comment by LambdAurora** [comment]
Seems like it's a Cardinal Components API issue, which Trinkets relies on.

I opened an issue on Cardinal Components API repository (OnyxStudios/Cardinal-Components-API#93).
In the meantime I recommend to downgrade Fabric API.

**Comment by dudematthew** [comment]
I'll try it on monday, thanks for advice 🚩

**Comment by dudematthew** [comment]
Working, can be closed now

**Comment by yupyup0666** [comment]
I'm having a similar issue:
https://paste.ee/p/AunEw
When adding an updated version of CCA it doesn't help either:
https://paste.ee/p/Xliik
